# Generated by Django 5.0.14 on 2026-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant Investi')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé')], default='ACTIVE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Produit (Ex: Pétrole Brut)')),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mise Minimum (XOF)')),
                ('daily_roi_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendement Quotidien (%)')),
                ('duration_months', models.IntegerField(default=10, verbose_name='Durée (Mois)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('icon', models.CharField(blank=True, help_text='Ex: ph-drop, ph-diamond', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('DEPOSIT', 'Dépôt (Inscription/Invest)'), ('WITHDRAWAL', 'Retrait'), ('ROI', 'Gains Rendement'), ('BONUS', 'Bonus Parrainage')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(blank=True, help_text='CinetPay, Orange Money...', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Validé'), ('FAILED', 'Échoué')], default='PENDING', max_length=15)),
                ('tx_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
