# Generated by Django 5.0.14 on 2026-03-31 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Booster (Ex: Speed Boost x1.5)')),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Multiplicateur (Ex: 1.5)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat (XOF)")),
                ('duration_days', models.IntegerField(default=1, verbose_name='Durée (Jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('icon', models.CharField(blank=True, help_text='Ex: ph-rocket', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.booster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
