# Generated by Django 5.0.14 on 2026-04-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_booster_userbooster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50, unique=True, verbose_name='Nom du Fournisseur (ex: CinetPay)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer ce moyen de paiement')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clé API Publique')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clé API Secrète / Token')),
                ('environment', models.CharField(choices=[('TEST', 'Sandbox / Test'), ('PROD', 'Production')], default='TEST', max_length=50)),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL de Webhook')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode Maintenance')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'inscription (XOF)")),
                ('default_roi_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Taux de rendement global par défaut (%)')),
                ('sponsor_bonus_level_1', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Bonus Parrainage Niveau 1 (%)')),
                ('sponsor_bonus_level_2', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Bonus Parrainage Niveau 2 (%)')),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Retrait Minimum (XOF)')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action effectuée')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Alerte'), ('CRITICAL', 'Critique')], default='INFO', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
