# Generated by Django 5.0.14 on 2026-04-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_paymentconfig_systemsettings_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booster',
            options={'verbose_name': 'Booster', 'verbose_name_plural': 'Boosters'},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Investissement', 'verbose_name_plural': 'Investissements'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userbooster',
            options={'verbose_name': 'Booster Utilisateur', 'verbose_name_plural': 'Boosters Utilisateur'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, help_text='CinetPay, Orange Money, Crypto Wallet...', max_length=255),
        ),
    ]
