# Generated by Django 5.2.3 on 2026-04-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0005_alter_booster_options_alter_investment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Nom (ex: Bronze, Argent)"
                    ),
                ),
                ("level", models.IntegerField(unique=True, verbose_name="Niveau")),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Emoji Badge (ex: 🥉)",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant Minimum"
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Montant Maximum",
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Taux journalier (ex: 0.012 = 1.2%)",
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Taux mensuel (ex: 0.36 = 36%)",
                    ),
                ),
                (
                    "cycle_days",
                    models.IntegerField(verbose_name="Durée du cycle (jours)"),
                ),
                (
                    "badge_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="Couleur Hexbadge",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icone CSS"
                    ),
                ),
                (
                    "advantages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Avantages (JSON)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Est actif"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Palier VIP",
                "verbose_name_plural": "Paliers VIP",
                "ordering": ["level"],
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="daily_rate_snapshot",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=5,
                verbose_name="Taux journalier figé",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investments.product",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investments.investmenttier",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="investments.investmenttier",
                verbose_name="Palier VIP lié",
            ),
        ),
    ]
