# Generated by Django 5.0.14 on 2026-04-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_investmenttier_investment_daily_rate_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
