# Generated by Django 5.0.14 on 2026-04-18 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_remove_investment_product_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_tx', to='investments.investment'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('PAY_INVEST', 'Achat de Palier (Checkout)'), ('WITHDRAWAL', 'Retrait'), ('ROI', 'Gains Rendement'), ('BONUS', 'Bonus Parrainage')], max_length=15),
        ),
    ]
