# Generated by Django 5.0.14 on 2026-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_update_transaction_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Souscription', 'verbose_name_plural': 'Souscriptions'},
        ),
        migrations.AlterModelOptions(
            name='investmenttier',
            options={'ordering': ['level'], 'verbose_name': "Categorie d'investissement", 'verbose_name_plural': "Categories d'investissement"},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action effectuee'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='duration_days',
            field=models.IntegerField(default=1, verbose_name='Duree (Jours)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='daily_rate_snapshot',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Taux journalier fige'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Termine')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emoji Badge (ex: medal)'),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='cycle_days',
            field=models.IntegerField(verbose_name='Duree du cycle (jours)'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cle API Publique'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cle API Secrete / Token'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_roi_percentage',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Taux de rendement global par defaut (%)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Valide'), ('FAILED', 'Echoue')], default='PENDING', max_length=15),
        ),
    ]
